### ISSUE TITLE
This project duplicates react-vendor-prefix

### ISSUE THREAD

**Issue by wmertens** [nmn/react-stylePrefixr#3]
https://github.com/cgarvis/react-vendor-prefix already does prefix fixing although the API is slightly different, it expects a keyed object of multiple styles.

It also supports flexbox prefixing which this project doesn't yet...

Perhaps better to team up and provide an extra API?

**Comment by nmn** [comment]
I like the idea. There are actually some more projects that do something similar. React itself does some of this already as well.

These two projects however work in similar enough ways that they should both continue to exist.

react-vendor-prefix is definitely in a better state than React-prefixr. But I like the React-prefixr name better.

I think I'm going to update React-prefixr to use your project as a dependency and add extra API on top. Slowly, we can transition over completely. Sounds good?

**Comment by wmertens** [comment]
It's not my project but that sounds like a good idea :-)

**Comment by nmn** [comment]
cool. expect pull requests from me soon.
